version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-server
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE : dbtest
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


