version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgres_local
    ports:
      - "5432:5432"
    environment:

      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: qkrgmlrud!1

    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin

  redis:
    image: redis
    container_name: email-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/var/lib/redis
